/* paises.js — De «Italia» a 🇮🇹.

   POR QUÉ EXISTE ESTE FICHERO. La tabla de nombre de país a código ISO vivía
   dentro del mapamundi, que era lo único que la usaba. Al quitar el mapa se
   iba con él una cosa que sí hace falta: los datos de un vuelo traen el país
   escrito («Reino Unido»), y para pintar una bandera hace falta el código.

   LA BANDERA ES EL PROPIO CÓDIGO. No hay imágenes ni CDN: un emoji de bandera
   son las dos letras ISO desplazadas al bloque de símbolos regionales del
   Unicode, así que 🇮🇹 pesa cero, lo dibuja el sistema y sigue estando sin
   cobertura. En Windows no hay glifo de bandera y salen las dos letras, que es
   un mal menor honesto: se sigue sabiendo de qué país habla.

   LOS NOMBRES LLEGAN COMO LLEGAN. Unos vienen del scraper en inglés y otros en
   español, con tildes y sin ellas. Se comparan pelados —sin tildes y en
   minúscula— y los que ni así cuadran van en `ALIAS`, a mano y contados. */

/* Sacada del mapa que había (`web/mapa.svg`), que traía los 225 países con su
   código puesto. Se genera una vez y se queda: los países no se mueven. */
const ISO = {
  "afganistan": "AF",
  "albania": "AL",
  "alemania": "DE",
  "andorra": "AD",
  "angola": "AO",
  "anguila": "AI",
  "antartida": "AQ",
  "antigua y barbuda": "AG",
  "arabia saudita": "SA",
  "argelia": "DZ",
  "argentina": "AR",
  "armenia": "AM",
  "aruba": "AW",
  "australia": "AU",
  "austria": "AT",
  "azerbaiyan": "AZ",
  "bahamas": "BS",
  "bahrein": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "belgica": "BE",
  "belice": "BZ",
  "benin": "BJ",
  "bermudas": "BM",
  "bielorrusia": "BY",
  "bolivia": "BO",
  "bosnia y herzegovina": "BA",
  "botswana": "BW",
  "brasil": "BR",
  "brunei darussalam": "BN",
  "bulgaria": "BG",
  "burkina faso": "BF",
  "burundi": "BI",
  "butan": "BT",
  "cabo verde": "CV",
  "camboya": "KH",
  "camerun": "CM",
  "canada": "CA",
  "catar": "QA",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "chipre": "CY",
  "colombia": "CO",
  "comoras": "KM",
  "congo": "CG",
  "congo (republica democratica del)": "CD",
  "costa de marfil": "CI",
  "costa rica": "CR",
  "croacia": "HR",
  "cuba": "CU",
  "curacao": "CW",
  "dinamarca": "DK",
  "dominica": "DM",
  "ecuador": "EC",
  "egipto": "EG",
  "el salvador": "SV",
  "emiratos arabes unidos": "AE",
  "eritrea": "ER",
  "eslovaquia": "SK",
  "eslovenia": "SI",
  "espana": "ES",
  "estados unidos": "US",
  "estonia": "EE",
  "esuatini": "SZ",
  "etiopia": "ET",
  "fiji": "FJ",
  "filipinas": "PH",
  "finlandia": "FI",
  "francia": "FR",
  "gabon": "GA",
  "gambia": "GM",
  "georgia": "GE",
  "georgia del sur y las islas sandwich del sur": "GS",
  "ghana": "GH",
  "granada": "GD",
  "grecia": "GR",
  "groenlandia": "GL",
  "guam": "GU",
  "guatemala": "GT",
  "guinea": "GN",
  "guinea bissau": "GW",
  "guinea ecuatorial": "GQ",
  "guyana": "GY",
  "haiti": "HT",
  "heard e islas mcdonald": "HM",
  "honduras": "HN",
  "hong kong": "HK",
  "hungria": "HU",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iraq": "IQ",
  "irlanda": "IE",
  "isla de man": "IM",
  "islandia": "IS",
  "islas aland": "AX",
  "islas caiman": "KY",
  "islas feroe": "FO",
  "islas malvinas": "FK",
  "islas marianas del norte": "MP",
  "islas marshall": "MH",
  "islas salomon": "SB",
  "islas turcas y caicos": "TC",
  "islas virgenes de los estados unidos": "VI",
  "israel": "IL",
  "italia": "IT",
  "jamaica": "JM",
  "japon": "JP",
  "jordania": "JO",
  "kazajistan": "KZ",
  "kenia": "KE",
  "kirguistan": "KG",
  "kiribati": "KI",
  "kuwait": "KW",
  "lesoto": "LS",
  "letonia": "LV",
  "libano": "LB",
  "liberia": "LR",
  "libia": "LY",
  "liechtenstein": "LI",
  "lituania": "LT",
  "luxemburgo": "LU",
  "macedonia del norte": "MK",
  "madagascar": "MG",
  "malasia": "MY",
  "malaui": "MW",
  "maldivas": "MV",
  "mali": "ML",
  "malta": "MT",
  "marruecos": "MA",
  "mauricio": "MU",
  "mauritania": "MR",
  "mexico": "MX",
  "micronesia": "FM",
  "moldavia": "MD",
  "mongolia": "MN",
  "montenegro": "ME",
  "montserrat": "MS",
  "mozambique": "MZ",
  "myanmar": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "nepal": "NP",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "niue": "NU",
  "noruega": "NO",
  "nueva caledonia": "NC",
  "nueva zelanda": "NZ",
  "oman": "OM",
  "paises bajos": "NL",
  "pakistan": "PK",
  "palau": "PW",
  "palestina": "PS",
  "panama": "PA",
  "papua nueva guinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "pitcairn": "PN",
  "polinesia francesa": "PF",
  "polonia": "PL",
  "portugal": "PT",
  "puerto rico": "PR",
  "reino unido": "GB",
  "republica arabe siria": "SY",
  "republica centroafricana": "CF",
  "republica checa": "CZ",
  "republica de corea": "KR",
  "republica democratica popular de lao": "LA",
  "republica dominicana": "DO",
  "republica popular democratica de corea": "KP",
  "ruanda": "RW",
  "rumania": "RO",
  "rusia": "RU",
  "sahara occidental": "EH",
  "saint kitts y nevis": "KN",
  "saint martin (francesa)": "MF",
  "samoa": "WS",
  "samoa americana": "AS",
  "san marino": "SM",
  "san pedro y miquelon": "PM",
  "san vicente y las granadinas": "VC",
  "santa helena, ascension y tristan de acuna": "SH",
  "santa lucia": "LC",
  "santo tome y principe": "ST",
  "senegal": "SN",
  "serbia": "RS",
  "seychelles": "SC",
  "sierra leona": "SL",
  "singapur": "SG",
  "sint maarten (neerlandesa)": "SX",
  "somalia": "SO",
  "sri lanka": "LK",
  "sudafrica": "ZA",
  "sudan": "SD",
  "sudan del sur": "SS",
  "suecia": "SE",
  "suiza": "CH",
  "suriname": "SR",
  "tailandia": "TH",
  "taiwan": "TW",
  "tanzania": "TZ",
  "tayikistan": "TJ",
  "territorio britanico del oceano indico": "IO",
  "tierras australes francesas": "TF",
  "timor-leste": "TL",
  "togo": "TG",
  "tonga": "TO",
  "trinidad y tobago": "TT",
  "tunez": "TN",
  "turkmenistan": "TM",
  "turquia": "TR",
  "ucrania": "UA",
  "uganda": "UG",
  "uruguay": "UY",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "venezuela": "VE",
  "vietnam": "VN",
  "yemen": "YE",
  "yibuti": "DJ",
  "zambia": "ZM",
  "zimbabue": "ZW",
};

/* Los que el scraper escribe en inglés. Son los que aparecen de verdad en los
   datos; si algún día sale otro, se añade aquí y ya. */
const ALIAS = {
  algeria: "DZ",
  azerbaijan: "AZ",
  luxembourg: "LU",
  "north macedonia": "MK",
  qatar: "QA",
  singapore: "SG",
  "south korea": "KR",
  "czech republic": "CZ",
  "bosnia and herzegovina": "BA",
  "bosnia & herzegovina": "BA",
};

const pelado = (s) =>
  String(s || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim()
    .toLowerCase();

/* El código ISO de un país, o "" si no se reconoce. */
export function isoDe(pais) {
  const q = pelado(pais);
  return ISO[q] || ALIAS[q] || "";
}

/* Y su bandera. Cadena vacía si no se sabe: mejor nada que un cuadrado roto. */
export function banderaDe(pais) {
  const iso = isoDe(pais);
  if (!iso) return "";
  // 0x1F1E6 es 🇦: el emoji sale de sumar la distancia de cada letra a la A.
  return String.fromCodePoint(...[...iso].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}
